"""added new topology connections and setup text boxes

Revision ID: 1bec1f8c3cd0
Revises: b65724438b5d
Create Date: 2023-07-05 21:48:13.168133

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1bec1f8c3cd0'
down_revision = 'b65724438b5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('topologies', schema=None) as batch_op:
        batch_op.alter_column('topology_connections_text',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('topology_setup_text',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('topologies', schema=None) as batch_op:
        batch_op.alter_column('topology_setup_text',
               existing_type=sa.String(length=255),
               type_=mysql.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('topology_connections_text',
               existing_type=sa.String(length=255),
               type_=mysql.TEXT(),
               existing_nullable=True)

    # ### end Alembic commands ###
