"""Added Topologies Model

Revision ID: 581843c73d29
Revises: 47a222b28e10
Create Date: 2023-05-08 20:48:23.868360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '581843c73d29'
down_revision = '47a222b28e10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('topologies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topology_name', sa.String(length=255), nullable=True),
    sa.Column('topology_description', sa.Text(), nullable=True),
    sa.Column('topology_creator', sa.String(length=255), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('topologies')
    # ### end Alembic commands ###
