"""changed the e columns values

Revision ID: 792d58713567
Revises: 7c034175136e
Create Date: 2023-07-08 16:59:23.671191

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '792d58713567'
down_revision = '7c034175136e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('topologies', schema=None) as batch_op:
        batch_op.alter_column('topology_controllers_nr',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('topology_routers_nr',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('topologies', schema=None) as batch_op:
        batch_op.alter_column('topology_routers_nr',
               existing_type=sa.String(length=255),
               type_=mysql.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('topology_controllers_nr',
               existing_type=sa.String(length=255),
               type_=mysql.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
