"""changed nullable to true

Revision ID: 7c034175136e
Revises: a09ed70b21c5
Create Date: 2023-07-08 16:49:29.882202

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7c034175136e'
down_revision = 'a09ed70b21c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('topologies', schema=None) as batch_op:
        batch_op.alter_column('topology_controllers_nr',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('topology_routers_nr',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('topologies', schema=None) as batch_op:
        batch_op.alter_column('topology_routers_nr',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('topology_controllers_nr',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
