"""foreign key

Revision ID: 80aab464e508
Revises: 581843c73d29
Create Date: 2023-05-20 20:49:09.608250

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '80aab464e508'
down_revision = '581843c73d29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('topologies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('topology_creator_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['topology_creator_id'], ['id'])
        batch_op.drop_column('topology_creator')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('topologies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('topology_creator', mysql.VARCHAR(length=255), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('topology_creator_id')

    # ### end Alembic commands ###
