"""added routers in topology form

Revision ID: b2cd35387d93
Revises: 1bec1f8c3cd0
Create Date: 2023-07-05 23:16:32.045951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2cd35387d93'
down_revision = '1bec1f8c3cd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('topologies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('topology_routers_nr', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('topology_routers_names', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('topologies', schema=None) as batch_op:
        batch_op.drop_column('topology_routers_names')
        batch_op.drop_column('topology_routers_nr')

    # ### end Alembic commands ###
