"""added fields for input names

Revision ID: b65724438b5d
Revises: ecdb0c85fa24
Create Date: 2023-06-25 17:15:06.441402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b65724438b5d'
down_revision = 'ecdb0c85fa24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('topologies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('topology_controllers_names', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('topology_switches_names', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('topology_hosts_names', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('topologies', schema=None) as batch_op:
        batch_op.drop_column('topology_hosts_names')
        batch_op.drop_column('topology_switches_names')
        batch_op.drop_column('topology_controllers_names')

    # ### end Alembic commands ###
