"""changed topologies form

Revision ID: ecdb0c85fa24
Revises: 80aab464e508
Create Date: 2023-06-25 14:47:36.884660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecdb0c85fa24'
down_revision = '80aab464e508'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('topologies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('topology_controllers_nr', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('topology_switches_nr', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('topology_hosts_nr', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('topology_creation_text', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('topologies', schema=None) as batch_op:
        batch_op.drop_column('topology_creation_text')
        batch_op.drop_column('topology_hosts_nr')
        batch_op.drop_column('topology_switches_nr')
        batch_op.drop_column('topology_controllers_nr')

    # ### end Alembic commands ###
