"""added new table

Revision ID: fa6338027fe3
Revises: 1951456c762c
Create Date: 2023-07-29 11:36:08.604010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa6338027fe3'
down_revision = '1951456c762c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('topologies_uploaded',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topology_name', sa.String(length=255), nullable=True),
    sa.Column('topology_description', sa.Text(), nullable=True),
    sa.Column('topology_file_path', sa.String(length=255), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('topology_creator_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['topology_creator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('topologies_uploaded')
    # ### end Alembic commands ###
